[[bin]]
name = "near-abi-gen"
path = "main.rs"

[dependencies]
serde_json = "1.0"

[dependencies.near-sdk]
default-features = false
features = ["abi"]
version = "4.1.0-pre.1"

[package]
build = "build.rs"
edition = "2021"
name = "near-abi-gen"
publish = false
version = "0.1.0"
[profile.dev]
debug = 0
lto = "off"
opt-level = 0

[workspace]
members = []
